apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    environment: {{ .Values.environment }}
    region: {{ .Values.region }}
data:
  LABELS: |
    {
      "region": "test",
      "test": "true"
    }
